[package]
name = "service_providers_utils"
version = "0.1.0"
edition = "2021"

[dependencies]
holochain_client = "0.8.0-dev"
holochain_types = "0.6.0-dev"
anyhow = "1"
holochain_serialized_bytes = "*"
serde = "1"
futures = "0.3"

service_providers_types = { path = "../service_providers_types" }
